#!/bin/bash

deepspeed llava/train/train_mem.py \
    --deepspeed /opt/data/private/eric/code/LLaVA/scripts/zero2.json \
    --model_name_or_path /opt/data/private/eric/model/llama/Sheared-Llama-1.3b \
    --version plain \
    --data_path /opt/data/private/eric/data/llava/LAION-CC-SBU_558k/blip_laion_cc_sbu_558k.json \
    --image_folder /opt/data/private/eric/data/llava/LAION-CC-SBU_558k/images/ \
    --vision_tower /opt/data/private/eric/model/clip/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir /opt/data/private/eric/save_model/llava \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100 \
    --save_total_limit 100 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
